from typing import Optional, List, Tuple, Dict

def get_languages() -> List[str]: ...
def get_synthesis_languages() -> List[str]: ...
def get_recognition_languages() -> List[str]: ...
def say(
    text: str, language: Optional[str] = None, rate: Optional[float] = 0.5
) -> None: ...
def stop() -> None: ...
def is_speaking() -> bool: ...
def recognize(
    file_path: str, language: Optional[str] = None
) -> List[Tuple[str, List[Dict]]]: ...
