from typing import List, Any, ByteString, Optional
from typing_extensions import Literal

def is_running_extension() -> bool: ...
def get_attachments(uti: str = "public.data") -> List[Any]: ...
def get_images(image_type: Literal["ui", "pil"] = "pil") -> List[Any]: ...
def get_image(image_type: Literal["ui", "pil"] = "pil") -> Any: ...
def get_image_data() -> Optional[ByteString]: ...
def get_images_data() -> List[ByteString]: ...
def get_text() -> str: ...
def get_urls() -> List[str]: ...
def get_url() -> Optional[str]: ...
def get_file_paths() -> List[str]: ...
def get_file_path() -> Optional[str]: ...
def get_vcard() -> Optional[Any]: ...
def get_vcards() -> List[Any]: ...
