from typing import Optional, Tuple
from typing_extensions import Literal

def clear() -> None: ...
def set_font(name: Optional[str], size: Optional[float]) -> None: ...
def set_color(r: float, g: float, b: float) -> None: ...
def secure_input(prompt: Optional[str]) -> None: ...
def show_image(image_path: str) -> None: ...
def alert(
    title: str,
    message: Optional[str],
    button1: Optional[str],
    button2: Optional[str],
    button3: Optional[str],
    hide_cancel_button: bool = False,
) -> int: ...
def input_alert(
    title: str,
    message: Optional[str],
    input: Optional[str],
    ok_button_title: Optional[str],
    hide_cancel_button: bool = False,
) -> str: ...
def password_alert(
    title: str,
    message: Optional[str],
    password: Optional[str],
    ok_button_title: Optional[str],
    hide_cancel_button: bool = False,
) -> str: ...
def login_alert(
    title: str,
    message: Optional[str],
    login: Optional[str],
    password: Optional[str],
    ok_button_title: Optional[str],
) -> Tuple[str, str]: ...
def show_activity() -> None: ...
def hide_activity() -> None: ...
def hud_alert(
    message: str, icon: Literal["success", "error"] = "success", duration: float = 1.8
) -> None: ...
def write_link(title: str, link_url: str) -> None: ...
def hide_output() -> None: ...
def quicklook(file_path: str) -> None: ...
def open_in(file_path) -> None: ...
def set_idle_timer_disabled(flag: bool) -> None: ...
def is_in_background() -> bool: ...
