name: Publish

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build
        run: uv build

      - name: Publish
        if: github.event_name == 'release'
        run: uv publish --trusted-publishing always
